### Create an array of 10 zeros

In [2]:
import numpy as np

In [4]:
arr1=np.zeros(10)

In [6]:
arr1

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

### Create an array of 10 ones

In [8]:
arr2=np.ones(10)

In [9]:
arr2

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

### Create an array of 10 fives

In [10]:
arr3=np.ones(10)*5

In [11]:
arr3

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [14]:
arr3=np.ones(10)+4

In [15]:
arr3

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

### Create an array of the integers from 10 to 50

In [21]:
arr4=np.arange(10,51)

In [22]:
arr4

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

### Create an array of all the even integers from 10 to 50

In [24]:
arr5=(arr4%2==0)

In [25]:
arr5

array([ True, False,  True, False,  True, False,  True, False,  True,
       False,  True, False,  True, False,  True, False,  True, False,
        True, False,  True, False,  True, False,  True, False,  True,
       False,  True, False,  True, False,  True, False,  True, False,
        True, False,  True, False,  True])

In [29]:
arr6=np.arange(10,51,2)

In [30]:
arr6

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

### Create a 3x3 matrix with values ranging from 0 to 8

In [37]:
arr7=np.arange(0,9).reshape(3,3)

In [38]:
arr7

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

### Create a 3x3 identity matrix

In [75]:
arr8=np.eye(3)

In [45]:
arr8

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### Use NumPy to generate a random number between 0 and 1 Discuss

In [78]:
arr9=np.random.rand()

In [79]:
arr9

0.5823052361614758

### Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution

In [82]:
arr10=np.random.randn(25)

In [83]:
arr10

array([-0.66922017, -1.2912572 , -1.4573393 , -1.69809042, -1.53101969,
       -0.3920923 ,  0.61747355,  0.58056394, -0.96175054,  0.99002485,
       -0.72089874, -1.27061761, -1.65061362,  1.47496012, -1.04862971,
       -1.42925964,  0.65822419,  0.36631682, -0.03781699, -1.22170095,
        0.85402197, -0.77380564, -0.67150325, -0.19642402, -1.02285541])

### Create the following matrix:

In [8]:
arr11=np.arange(0.01,1.01,0.01)

In [9]:
arr11

array([0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 , 0.11,
       0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 , 0.21, 0.22,
       0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 , 0.31, 0.32, 0.33,
       0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 , 0.41, 0.42, 0.43, 0.44,
       0.45, 0.46, 0.47, 0.48, 0.49, 0.5 , 0.51, 0.52, 0.53, 0.54, 0.55,
       0.56, 0.57, 0.58, 0.59, 0.6 , 0.61, 0.62, 0.63, 0.64, 0.65, 0.66,
       0.67, 0.68, 0.69, 0.7 , 0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77,
       0.78, 0.79, 0.8 , 0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88,
       0.89, 0.9 , 0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99,
       1.  ])

### Create an array of 20 linearly spaced points between 0 and 1:

In [98]:
arr12=np.linspace(0,1,20)

In [99]:
arr12

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

# Numpy Indexing and Selection

In [100]:
arr13=np.arange(1,26).reshape(5,5)

In [101]:
arr13

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [103]:
arr13[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [109]:
arr13 [3:4,4:]

array([[20]])

In [110]:
arr13[:3,1:2]

array([[ 2],
       [ 7],
       [12]])

In [111]:
arr13[4:]

array([[21, 22, 23, 24, 25]])

In [112]:
arr13

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [113]:
arr13[3:]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

### Get the sum of all the values in mat

In [114]:
arr13.sum()

325

#### Get the standard deviation of the values in mat

In [115]:
arr13.std()

7.211102550927978

### Get the sum of all the columns in mat

In [119]:
arr13.sum(axis=1).reshape(5,1)

array([[ 15],
       [ 40],
       [ 65],
       [ 90],
       [115]])

In [120]:
arr13[:,4:]

array([[ 5],
       [10],
       [15],
       [20],
       [25]])